export enum NodeKeys {
    ID = 'id',
    UID = 'uid',
    DESCRIPTION = 'description',
    DESCRIPTOR = 'descriptor',
    DEPRECATED = 'deprecated',
    EXTENDED_COLUMN = 'extendedColumn',
    ANCHOR_ROLE = 'anchorRole',
    TIME_RANGE = 'timeRange',
    KNOT_RANGE = 'knotRange',
    MNEMONIC = 'mnemonic',
    DATA_RANGE = 'dataRange',
    LENGTH = 'length',
    INDEXES = 'indexes',
    TYPE = 'type',
    JSON = 'json',
    LAYERED = 'layered',
    PRECISION = 'precision',
    SCALE = 'scale',
    SKIP = 'skip',
    KNOT_ROLE = 'knotRole',
    IDENTITY = 'identity'
}